# ************************************************************************** #
#                                                                            #
#                                                        :::      ::::::::   #
#   Makefile                                           :+:      :+:    :+:   #
#                                                    +:+ +:+         +:+     #
#   By: sanghjeo <sanghjeo@student.42seoul.kr>     +#+  +:+       +#+        #
#                                                +#+#+#+#+#+   +#+           #
#   Created: 2022/07/07 13:03:15 by sanghjeo          #+#    #+#             #
#   Updated: 2022/07/07 13:03:15 by sanghjeo         ###   ########.fr       #
#                                                                            #
# ************************************************************************** #

CC = gcc
CFLAGS = -Wall -Wextra -Werror
INC = libft.h

NAME = libft.a
SRC = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcpy.c  ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c
SRC_BONUS = ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJ = $(SRC:%.c=%.o)
OBJ_BONUS = ${SRC_BONUS:%.c=%.o}

ifdef FLAG
OBJ_FILES = $(OBJ) $(OBJ_BONUS)
else
OBJ_FILES = $(OBJ)
endif

%.o : %.c 
	$(CC) $(CFLAGS) -c $< -o $@ -I $(INC)

$(NAME) : $(OBJ_FILES)
	ar rcs $@ $^

all : $(NAME)

bonus :
	FLAG=1 make all

clean : 
	rm -f $(OBJ) $(OBJ_BONUS)

fclean : clean
	rm -f $(NAME)

re : fclean all

.PHONY: clean fclean re all bonus